spring:
  datasource:
#    platform: mysql
#    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deputy?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234