CREATE TABLE IF NOT EXISTS DEPUTY_PRESENCE
(
    ID        BIGINT AUTO_INCREMENT,
    DEPUTY_ID INT,
    NAME      VARCHAR(255),
    PARTY     VARCHAR(255),
    PRIMARY KEY (ID)

);

CREATE TABLE IF NOT EXISTS DEPUTY_FULL_INFO
(
    ID             BIGINT AUTO_INCREMENT,
    DEPUTY_ID      INT,
    FULL_NAME      VARCHAR(255),
    ELECTED_IN     VARCHAR(255),
    ELECTED_IN_OUT VARCHAR(255),
    PARTY          VARCHAR(255),
    POST           VARCHAR(255),
    BIRTHDAY       VARCHAR(255),
    ABOUT          VARCHAR(255),
    PRESENT        VARCHAR(255),
    PRESENT_ELEC   VARCHAR(255),
    ABSENT_ELEC    VARCHAR(255),
    WAS_ILL        VARCHAR(255),
    VACATION       VARCHAR(255),
    TRIP           VARCHAR(255),
    WAS_ABSENT     VARCHAR(255),
    DEP_IMAGE      VARCHAR(255),
    DEP_SHORT_NAME VARCHAR(255),
    PRIMARY KEY (ID)
)